
/*
  Rahbany, Nicholas
  Guessing Game, where user guesses number generated by computer
  CS101
  10/26/17
*/

import java.util.*;

public class TemplateUpdated {
  /* 
  
  main(args) 
    in = Scanner Object
    random = Random Object
    guesses = 0
    check = “not true”
    playAgain = “no”
    guessAgain =”no”
    do
    	ask for maximum range for random number
    	read range
    	if range < 10
    		range = 10
    	magicNumber = random number in from 0 to range
    	ask user for how many guesses
    	guesses =  read guesses
    	do
    		ask user for guess
    		read guess
    		check = numChecker guess and magicNumber
    		if check is not true
    			print out check
    			add one to guesses
    			ask user to play again
    			read guessAgain
    			guessAgain to lower case
    		else
    			print congratulations
    			print number of guesses
    	while check is not true or guessAgain is yes
    	ask user to play again
    	read playAgain
     playAgain to lower case
    while playAgain is yes
  
  */

  /* 
  
  Variable	  Type	         Purpose
  args	     String[]	      Parameter, unused
  check	     String	         If magicNumber = guess
  playAgain	  String	         If user wants to play again
  in	        Scanner	      Scans console for user input
  random	     Random	         Generates random number
  range	     int	            Upper range of random number
  magicNumber int	            Computer generated random number
  guesses	  int	            How many times a user can guess magicNumber
  
  */
  public static void main(String[] args) {
    Scanner in = new Scanner(System.in);
    Random random = new Random();
    int guesses = 0;
    String check = "not true";
    String playAgain = "no";
    String guessAgain = "no";
    do {
      System.out.println("What is the maximum range for your random number?");
      int range = in.nextInt();
      if (range < 10) {
        range = 10;
      }
      int magicNumber = random.nextInt(range) + 1;
      do {
        System.out.println("What is your guess?");
        int guess = in.nextInt();
        check = numChecker(guess, magicNumber);
        if (!check.equals("true")) {
          System.out.println(check);
          guesses++;
          System.out.println("Would you like to guess again? Type yes or no");
          guessAgain = in.next();
          guessAgain.toLowerCase();
        } else {
          System.out.println("Congratulations! You won!");
          System.out.println("You guessed the number in " + guesses + " guesses!");
        }
      } while ((!check.equals("true") && guessAgain.equals("yes"))
          || (check.equals("true") && !guessAgain.equals("yes")));
      System.out.println("Would you like to play again? Type yes or no");
      playAgain = in.next();
      playAgain.toLowerCase();
    } while (playAgain.equals("yes"));

  }

  /* 
  
  numChecker (int userGuess, int shouldBe)
    result = no input
    if userGuess equals shouldBe
  	  result = true
    else
  	  if userGuess is greater
  		  result = too high
  	  else
  		  result = too low
    return result
  
  */

  /* 

  Variable	 Type	   Purpose
  userguess	 int	   The number the user guessed
  shouldBe	 int	   magicNumber for different method
  result	    String	Used as return variable in numCheck

  */
  public static String numChecker(int userGuess, int shouldBe) {
    String result = "no input";
    if (userGuess == shouldBe) {
      result = "true";
    } else {
      if (userGuess > shouldBe) {
        result = "too high";
      } else {
        result = "too low";
      }
    }
    return result;
  }

}